/***************************************************************************
 * ELSETYPE.H - Basic types used by the ElseWare PANOSE(tm) Font Mapper.
 *
 * $keywords: elsetype.h 1.0  3-Feb-92 4:58:10 PM$
 *
 * Copyright (C) 1991 ElseWare Corporation.  All rights reserved.
 ***************************************************************************/

#ifndef _elsetype_def
#define _elsetype_def

#define INT int
#define LONG long
#define VOID void

typedef int BOOL;
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned int UINT;
typedef unsigned long ULONG;

#endif

/***************************************************************************
 * Revision log:
 ***************************************************************************/
/*
 * $lgb$
 * 1.0     3-Feb-92  msd Version 1.00 mapper placed under version control.
 * $lge$
 */

