#define WIN31
#define WINVER 0x030a
#define _WINDLL
#define STRICT
#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <cderr.h>
#include <ddeml.h>
#include <time.h>
#include <io.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <memory.h>
#include "..\..\inc\wdb.h"
#include "..\..\inc\struct.h"   // must be included first
#include "..\..\inc\ascii.h"
#include "..\..\inc\conxlib.h"
#include "..\..\inc\FCDB.h"
#include "..\..\inc\conxmem.h"

