#define IDD_OK                      IDOK
#define IDD_CANCEL                  IDCANCEL
#define SETTINGSDLGBOX              100
#define ICONS                       101

#define IDD_LOCALNAME               0x0100
#define IDD_REMOTENAME              0x0101
#define IDD_SERVERMODE              0x0102
#define IDD_BLANKPAD                0x0103
#define IDD_RXTIMEOUT               0x0104
#define IDD_TXTIMEOUT               0x0105
#define IDD_STANDARD                0x0106
#define IDD_UB                      0x0107
#define IDD_DLGFRAME                0x0108

#define IDS_SETTINGS_LOCALNAME      0x2000
#define IDS_SETTINGS_REMOTENAME     0x2001
#define IDS_SETTINGS_SERVERMODE     0x2002
#define IDS_SETTINGS_BLANKPAD       0x2003
#define IDS_SETTINGS_RXTIMEOUT      0x2004
#define IDS_SETTINGS_TXTIMEOUT      0x2005
#define IDS_SETTINGS_EXTENSION      0x2006

#define IDS_DEFAULT_LOCALNAME       0x2100
#define IDS_DEFAULT_REMOTENAME      0x2101
#define IDS_DEFAULT_SERVERMODE      0x2102
#define IDS_DEFAULT_BLANKPAD        0x2103
#define IDS_DEFAULT_RXTIMEOUT       0x2104
#define IDS_DEFAULT_TXTIMEOUT       0x2105
#define IDS_DEFAULT_EXTENSION       0x2106
