MEM      =-AM
LIB      =mlibcaw
CLOPTS   =$(MEM) -c -Gsw -Oad -Zpei -W3 -FPa -nologo -D DEBUG
LINKOPTS =/NOD/NOE/CO

all: test.exe

test.res: test.rc test.ico gennum.dlg
    rc -r test.rc

test.obj: test.c test.h testd.h
    cl $(CLOPTS) test.c > test.err

test.exe: test.obj test.def test.res
    link $(LINKOPTS) test,,, ..\lexmac libw $(LIB), test.def
    rc -v test.res
