LPARAM CALLBACK fnMain( HWND hDlg, UINT uiMsg, WPARAM wParam, LPARAM lParam) ;
HICON WINAPI SetDlgIcon( HWND hDlg, UINT wID, HICON hIcon ) ;

#define WM_MYINIT 0x0401
#define WM_GO   0x0402
#define MK_f   102
#define MK_F   70
#define MK_o   111
#define MK_O   79
#define MK_h   72
#define MK_H   104

#define IDI_WINPRINT    1
#define IDI_PORTRAIT    2
#define IDI_LANDSCAPE   3
#define IDI_NOORIENT    4

#define ID_RCDATA_ORDER_FRM   1
