/* D:\LEXIS\MACROS\DLL\LEXMACD.H 11/28/1990 21:13*/
#define  IDD_BOX0	10
#define  IDD_CLIENT	100
#define  IDD_PAGES	101
#define  IDD_TIMEOUT	102
#define  IDD_LEXSEE	103
#define  IDD_LEXSTAT	104
#define  IDD_AUTOCITE	105
#define  IDD_SHEPARDS	106
#define  IDD_ABOUT	107
#define  IDD_LOGOFF	108
#define  IDD_SELECTION	109
#define  IDD_VERSION 110
#define  IDD_BOX1	11
#define  IDD_BOX2	12
#define  IDD_BOX3	13
#define  IDOK 1
#define  IDCANCEL	2
