//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by COLSAMP.RC
//
#define IDR_MAINFRAME                   2
#define IDR_COLSAMPTYPE                 3
#define IDR_COLSAMPTYPE_SRVR_IP         4
#define IDS_INI_CONFIG                  4
#define IDR_COLSAMPTYPE_SRVR_EMB        5
#define IDS_INI_MAINWNDPOS              5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_SIZEHORZ                    102
#define IDD_ADDITEM                     103
#define IDC_NAME                        1000
#define IDC_TYPE                        1001
#define IDC_VALUE                       1002
#define ID_EDIT_ADDITEM                 32771
#define ID_EDIT_REMOVEITEM              32772
#define ID_EDIT_CHANGEITEM              32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
