/************************************************************************
 *
 *     Project:  CONXLIB
 *
 *      Module:  dlgs.h
 *
 *     Remarks:  Dialog resource ids
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/
#define DLG_CUSTOMERINFO            10
#define DLG_SHIPPINGINFO            11
#define DLG_BILLINGINFO             12
#define DLG_COMMSETTINGS            13
#define DLG_DOWNLOAD                14
#define DLG_NEWPASSWORD             15
#define DLG_USERID                  16
#define DLG_ORDERINFO               17

#define IDD_HELP                    8

#define IDD_NAME_LBL                100
#define IDD_NAME                    101
#define IDD_COMPANYNAME_LBL         102
#define IDD_COMPANYNAME             103
#define IDD_STREET1_LBL             104
#define IDD_STREET1                 105
#define IDD_STREET2_LBL             106
#define IDD_STREET2                 107
#define IDD_CITY_LBL                108
#define IDD_CITY                    109
#define IDD_STATE_LBL               110
#define IDD_STATE                   111
#define IDD_ZIP_LBL                 112
#define IDD_ZIP                     113
#define IDD_COUNTRY_GRP             114
#define IDD_USA                     115
#define IDD_CANADA                  116
#define IDD_OTHER                   117
#define IDD_OTHEREDIT               118
#define IDD_AREACODE_LBL            119
#define IDD_OPEN_PAREN              120
#define IDD_AREACODE                121
#define IDD_CLOSE_PAREN             122
#define IDD_PHONENUMBER             123
#define IDD_EXTENSION_LBL           124
#define IDD_EXTENSION               125

#define IDD_1TO2DAY                 201
#define IDD_2TO3DAY                 202
#define IDD_UPS                     203
#define IDD_USECUSTADDRESS          204

#define IDD_SAVE                    300
#define IDD_MASTERCARD              301
#define IDD_VISA                    302
#define IDD_DISCOVER                303
#define IDD_AMEX                    304
#define IDD_CORPACCT                305
#define IDD_CARDNUMBER              306
#define IDD_NAMEONCARD              307
#define IDD_EXPMONTH                308
#define IDD_EXPYEAR                 309

#define IDD_206                     400
#define IDD_BBSNUMBER               401
#define IDD_DIALPREFIX              402
#define IDD_DIALSUFFIX              403
#define IDD_PORT                    404
#define IDD_BAUDRATE                405
#define IDD_MODEM                   406

#define IDD_PRODUCTS                501
#define IDD_AMEXSURCHARGELBL        502
#define IDD_SELECTBILLING           503
#define IDD_PRICE                   504
#define IDD_AMEXSURCHARGE           505
#define IDD_SALESTAX                506
#define IDD_TOTAL                   507
                                      
#define IDD_DIALSTRING              508
#define IDD_TONE                    509
#define IDD_PULSE                   510
#define IDD_TEXT                    511
#define IDD_TEXT1                   512

#define IDD_USERID                  513
#define IDD_CURPASSWORD             514
#define IDD_NEWPASSWORD1            515
#define IDD_NEWPASSWORD2            516
#define IDD_BILLINGMETHOD           517
#define IDD_ACCOUNTNUMBER           518
#define IDD_EXPDATE                 519
#define IDD_SHIPPING_GROUP          520
#define IDD_CUSTADDRESS             521
#define IDD_SHIPPINGMETHOD          522
#define IDD_BILLINGINFO             523
#define IDD_COUNTRY                 524
#define IDD_PHONE                   525
#define IDD_BILLING_GROUP           526

#define IDD_NOYIELD                 527

#define IDD_MEDIA                   19
#define IDD_TEXT2                   18
