#define SETTINGSDLGBOX              100
#define ICONS                       101

#define IDD_LOCALECHO               0x0100
#define IDD_NEWLINE                 0x0101
#define IDD_LINEWRAP                0x0102
#define IDD_SENDDEL                 0x0103
#define IDD_USENUMLOCK              0x0104
#define IDD_FONT                    0x0105

#define IDS_SETTINGS_LOCALECHO    0x0106  0x2000
#define IDS_SETTINGS_NEWLINE        0x2001
#define IDS_SETTINGS_LINEWRAP       0x2002
#define IDS_SETTINGS_SENDDEL        0x2003
#define IDS_SETTINGS_USENUMLOCK     0x2004

#define IDS_DEFAULT_LOCALECHO       0x2100
#define IDS_DEFAULT_NEWLINE         0x2101
#define IDS_DEFAULT_LINEWRAP        0x2102
#define IDS_DEFAULT_SENDDEL         0x2103
#define IDS_DEFAULT_USENUMLOCK      0x2104

