#define IDD_OK                      IDOK
#define IDD_CANCEL                  IDCANCEL

#define SETTINGSDLGBOX              100
#define ICONS                       101

#define IDD_LOCALECHO               0x0100
#define IDD_NEWLINE                 0x0101
#define IDD_LINEWRAP                0x0102
#define IDD_BASEFONT                0x0105
#define IDD_HIGHLIGHTFONT           0x0106
#define IDD_SAMPLE                  0x0107
#define IDD_DLGFRAME                0x0109

#define IDS_SETTINGS_LOCALECHO      0x2000
#define IDS_SETTINGS_NEWLINE        0x2001
#define IDS_SETTINGS_LINEWRAP       0x2002
#define IDS_SETTINGS_NFACENAME      0x2005
#define IDS_SETTINGS_NFACESIZEX     0x2006
#define IDS_SETTINGS_NFACESIZEY     0x2007
#define IDS_SETTINGS_NFGCOLOR       0x2008
#define IDS_SETTINGS_NBGCOLOR       0x2009
#define IDS_SETTINGS_HFACENAME      0x200A
#define IDS_SETTINGS_HFACESIZEX     0x200B
#define IDS_SETTINGS_HFACESIZEY     0x200C
#define IDS_SETTINGS_HFGCOLOR       0x200D
#define IDS_SETTINGS_HBGCOLOR       0x200E

#define IDS_DEFAULT_LOCALECHO       0x2100
#define IDS_DEFAULT_NEWLINE         0x2101
#define IDS_DEFAULT_LINEWRAP        0x2102
#define IDS_DEFAULT_NFACENAME       0x2105
#define IDS_DEFAULT_NFACESIZEX      0x2106
#define IDS_DEFAULT_NFACESIZEY      0x2107
#define IDS_DEFAULT_NFGCOLOR        0x2108
#define IDS_DEFAULT_NBGCOLOR        0x2109
#define IDS_DEFAULT_HFACENAME       0x210A
#define IDS_DEFAULT_HFACESIZEX      0x210B
#define IDS_DEFAULT_HFACESIZEY      0x210C
#define IDS_DEFAULT_HFGCOLOR        0x210D
#define IDS_DEFAULT_HBGCOLOR        0x210E
