/*****************************************************************************
* FILE NAME:  disconn.h                                                      *
*                                                                            *
* DESCRIPTIVE TITLE:                                                         *
*                                                                            *
*   disconnect from the OLS                                                  *
*                                                                            *
*                                                                            *
* DESCRIPTION:                                                               *
*                                                                            *
*   Disconnect    - Disconnects from the OLS                                 *
*                                                                            *
*                                                                            *
* DATA STRUCTURES                                                            *
*                                                                            *
*   none                                                                     *
*                                                                            *
*                                                                            *
* CAUTIONS:  none                                                            *
*                                                                            *
* RETURNS:                                                                   *
*                                                                            *
*   SUCCESS if successful and FAILURE if failed to disconnect.               *
*                                                                            *
*                                                                            *
* AUTHOR:  Dean Myers                                                        *
*                                                                            *
* DATE:  07/05/90                                                            *
*                                                                            *
* =========================================================================  *
*           M E A D   D A T A   C E N T R A L ,   I N C .                    *
*                          CONFIDENTIAL                                      *
*                                                                            *
* This document is property of Mead Data Central, Inc. (MDC) and its         *
* contents are proprietary to MDC.  Reproduction in any form by anyone       *
* of the materials combined herein without the permission of MDC is          *
* prohibited.  Finders are asked to return this document to Mead Data        *
* Central, Inc. at P.O. BOX 933, Dayton, OH 45401.                           *
*                                                                            *
*****************************************************************************/

/*
 *  $Log:   N:/src/disconn.h_v  $
   
      Rev 8.0   18 Dec 1990 10:56:34   joeb
   TURBO NEXIS VERSION 1.00 CERTIFIED AT ITERATION #5I -- REVISION 8.0
   
      Rev 7.0   06 Dec 1990 15:18:24   joeb
   revision 7.0 for iteration 5
   
      Rev 6.0   19 Nov 1990  9:23:06   joeb
   revision 6 for interation 4
   
      Rev 5.0   24 Oct 1990  9:06:44   andrews
   No change.
   
      Rev 4.0   01 Oct 1990 13:24:34   andrews
   ITERATION NUMBER 2
   
      Rev 3.0   17 Sep 1990 10:06:58   andrews
   Full Iteration 1
   
      Rev 2.0   27 Aug 1990  9:20:58   andrews
   iteration 1
   
      Rev 0.0   25 Jul 1990 14:57:06   deanm
   Initial revision.
 *
*/


#ifndef DISCONN_H
#define DISCONN_H


extern INT  Disconnect (void);

#endif

