/************************************************************************
 *
 *     Project:  WINPRINT 2.0
 *
 *      Module:  isz.h
 *
 *     Remarks:  String resource constants
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/

#ifndef _ISZ_H_
#define _ISZ_H_

/*
 * IDS values from FIRST_IDS to LAST_IDS are preloaded.
 */
#define FIRST_IDS 0

#define IDS_APPNAME              (FIRST_IDS + 0)
#define IDS_VERSION              (FIRST_IDS + 1)
#define IDS_INI_FILENAME         (FIRST_IDS + 2)
#define IDS_INI_MAIN             (FIRST_IDS + 3)
#define IDS_INI_REG              (FIRST_IDS + 4)
#define IDS_INI_REG_NAME         (FIRST_IDS + 5) 
#define IDS_INI_REG_CODE         (FIRST_IDS + 6)
#define IDS_INI_OPTIONS          (FIRST_IDS + 7)
#define IDS_INI_OPTIONS_SPEC     (FIRST_IDS + 8)
#define IDS_DEFAULTOPT           (FIRST_IDS + 9)
#define IDS_INI_POS              (FIRST_IDS + 10)
#define IDS_INI_POS_SPEC         (FIRST_IDS + 11)
#define IDS_DEFAULTFONT          (FIRST_IDS + 12)
#define IDS_INI_FONT             (FIRST_IDS + 13)
#define IDS_INI_FONT_SPEC        (FIRST_IDS + 14)
#define IDS_INI_WSHOW            (FIRST_IDS + 15)

#define IDS_HELPFILE                (FIRST_IDS + 16)
#define IDS_HEXWORD                 (FIRST_IDS + 17)
#define IDS_HEXDWORD                (FIRST_IDS + 18)
#define IDS_PLEASEPAY               (FIRST_IDS + 19)
#define IDS_APPTITLE                (FIRST_IDS + 20)


#define LAST_IDS (FIRST_IDS + 20)

#define IDS_ERR_CONFIRMDELETE       512
#define IDS_MSG_WORKING             515
#define IDS_MSG_PRINTERONPORT       516
#define IDS_ERR_PRINTERR            517
#define IDS_ERR_PRINTERR0           518
#define IDS_ERR_PRINTERR1           519
#define IDS_ERR_PRINTERR2           520
#define IDS_ERR_PRINTERR3           521
#define IDS_ERR_PRINTERR4           522
#define IDS_ERR_BADPRINTERDC        523
#define IDS_ERR_NOMEMORY            524
#define IDS_ERR_COMMANDLINE         525

#define IDS_ERR_SAVECHANGES         526
#define IDS_ERR_BADREGISTRATION     527
#define IDS_ERR_OPENFILE            528
#define IDS_ERR_BADEDITOR           529
#define IDS_ERR_BADDLLVER           530
#define IDS_ERR_SAVEOTHERFILE       531

#define IDS_MSG_PRINTING            540

#define IDS_PDERR_PRINTERCODES      550
#define IDS_PDERR_SETUPFAILURE      551
#define IDS_PDERR_PARSEFAILURE      552
#define IDS_PDERR_RETDEFFAILURE     553
#define IDS_PDERR_LOADDRVFAILURE    554
#define IDS_PDERR_GETDEVMODEFAIL    555
#define IDS_PDERR_INITFAILURE       556
#define IDS_PDERR_NODEVICES         557
#define IDS_PDERR_NODEFAULTPRN      558
#define IDS_PDERR_DNDMMISMATCH      559
#define IDS_PDERR_CREATEICFAILURE   560
#define IDS_PDERR_PRINTERNOTFOUND   561
#define IDS_CDERR_GENERALCODES      562
                                 

/* these are used by WinTime */
#define  IDS_SUNDAY	1024
#define  IDS_MONDAY	1025
#define  IDS_TUESDAY	1026
#define  IDS_WEDNESDAY	1027
#define  IDS_THURSDAY	1028
#define  IDS_FRIDAY	1029
#define  IDS_SATURDAY	1030
#define  IDS_SUNDAY_SHORT	1031
#define  IDS_MONDAY_SHORT	1032
#define  IDS_TUESDAY_SHORT	1033
#define  IDS_WEDNESDAY_SHORT	1034
#define  IDS_THURSDAY_SHORT	1035
#define  IDS_FRIDAY_SHORT	1036
#define  IDS_SATURDAY_SHORT	1037

#define  IDS_JANUARY	1040
#define  IDS_FEBURARY	1041
#define  IDS_MARCH	1042
#define  IDS_APRIL	1043
#define  IDS_MAY	1044
#define  IDS_JUNE	1045
#define  IDS_JULY	1046
#define  IDS_AUGUST	1047
#define  IDS_SEPTEMBER	1048
#define  IDS_OCTOBER	1049
#define  IDS_NOVEMBER	1050
#define  IDS_DECEMBER	1051

#define  IDS_JANUARY_SHORT	1056
#define  IDS_FEBURARY_SHORT	1057
#define  IDS_MARCH_SHORT	1058
#define  IDS_APRIL_SHORT	1059
#define  IDS_MAY_SHORT	1060
#define  IDS_JUNE_SHORT	1061
#define  IDS_JULY_SHORT	1062
#define  IDS_AUGUST_SHORT	1063
#define  IDS_SEPTEMBER_SHORT	1064
#define  IDS_OCTOBER_SHORT	1065
#define  IDS_NOVEMBER_SHORT	1066
#define  IDS_DECEMBER_SHORT	1067

#define  IDS_LONGDATE         1068
#define  IDS_SHORTDATE        1069

/* menu strings (help)     */
/* menu IDs begin at 4096  */


#endif

/************************************************************************
 * End of File: isz.h
 ***********************************************************************/

