#ifndef _MENU_H_
#define _MENU_H_

#define IDD_JOBNAME  100
#define IDD_MESSAGE  101

#define IDMYMENU     1


#define IDM_GETFOCUS     51
#define IDM_GETCOUNT     52
#define IDM_GETFILE      53
#define IDM_GETDRIVE     54
#define IDM_LFN          55
#define IDM_MULTIPLE     56
#define IDM_REFRESH      57
#define IDM_REFRESHALL   58
#define IDM_RELOAD       59


#define IDM_PRINT                   1
#define IDM_PRINTERSETUP            2
#define IDM_PAGELAYOUT              3
#define IDM_OPTIONS                 4
#define IDM_OPENCONFIG              5   
#define IDM_SAVECONFIG              6  
#define IDM_CURRENTCONFIG           7
#define IDM_HELP                    8
#define IDM_HELPONHELP              9
#define IDM_ABOUT                   10
#define IDM_COPYRIGHT               11
#define IDM_ALLRIGHTSRESERVED       12
#define IDM_CURRENTCONFIGLBL        13

#endif
