/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  APACHE, Apache For Windows
 *
 *      Module:  emutop.h
 *
 *   Author(s):  Bryan A. Woodruff (baw)
 *               Charles E. Kindel, Jr. (cek)
 *
 *
 *     Remarks:  Session window top status line
 *
 *   Revisions:  
 *     01.00.000  6/19/91 baw   Wrote it.
 *
 ************************************************************************/

// function prototypes (private)

BOOL CreateEmuTopStatus( HWND ) ;
BOOL DestroyEmuTopStatus( HWND ) ;
VOID SetupEmuTopBoxes( HWND ) ;

/************************************************************************
 * End of File: emutop.h
 ************************************************************************/

