/************************************************************************
 *
 *    Copyright (C) 1991 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  APACHE, Apache For Windows
 *
 *      Module:  ini.h
 *
 *   Author(s):  Bryan A. Woodruff (baw)
 *               Charles E. Kindel, Jr. (cek)
 *
 *
 *     Remarks:  Miscellaneous INI file stuff
 *
 *   Revisions:
 *     01.00.000  6/25/91 baw   Wrote this comment block.
 *
 ************************************************************************/

// function prototypes (private)

VOID FlushINIFile( LPSTR ) ;

/************************************************************************
 * End of File: ini.h
 ************************************************************************/


