/************************************************************************
 *
 *     Project:  APACHE for Windows
 *
 *      Module:  init.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/

#define MAXLEN_TITLE  64

BOOL FAR PASCAL InitApplication( HANDLE ) ;
BOOL FAR PASCAL InitInstance( HANDLE, int ) ;

/************************************************************************
 * End of File: init.h
 ***********************************************************************/

