/************************************************************************
 *
 *     Project:  
 *
 *      Module:  mdi.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/
HWND FAR PASCAL CreateMDIClient( HWND hwnd ) ;
LONG FAR PASCAL NewMDIClientProc( HWND hwnd, UINT uMsg,
                                  WPARAM wParam, LPARAM lParam ) ;


/************************************************************************
 * End of File: mdi.h
 ***********************************************************************/

