/************************************************************************
 *
 *     Project:  
 *
 *      Module:  misc.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/

WORD FAR PASCAL StatMax( WORD w1, WORD w2) ;

BOOL FAR PASCAL 
GetKeyStates( BOOL *pfCapsLock, BOOL *pfNumLock, BOOL *pfScrollLock ) ;

VOID FAR PASCAL SetKeyStatus( HWND hwndMsg ) ;

/************************************************************************
 * End of File: misc.h
 ***********************************************************************/

