//***************************************************************************
//
//  Module: precomp.h
//
//  Purpose:
//
//
//
//  Description of functions:
//
//
//
//  Development Team:
//     Bryan A. Woodruff
//
//  History:   Date       Author      Comment
//              1/25/92   BryanW      Modified make for precompiled headers
//
//---------------------------------------------------------------------------
//
//  *** ***  THIS CODE IS CONFIDENTIAL PROPERTY OF WERNER ASSOCIATES *** *** 
//  Copyright (c) 1992 Werner Associates.  All Rights Reserved.
//
//***************************************************************************

#define STRICT

#include <windows.h>
#include <commdlg.h>
#include <shellapi.h>
#include <wdb.h>

#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>

//***************************************************************************
//  End of File: precomp.h
//***************************************************************************

