/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  APACHE, Apache For Windows
 *
 *      Module:  setup.h
 *
 *   Author(s):  Bryan A. Woodruff (baw)
 *               Charles E. Kindel, Jr. (cek)
 *
 *
 *     Remarks:  Dialog setup functions
 *
 *   Revisions:  
 *     01.00.000  6/27/91 baw   Wrote it.
 *
 ************************************************************************/

// function prototypes (private)

BOOL DlgConnectorSetup( HWND, LPSTR, int ) ;
BOOL DlgEmulatorSetup( HWND, LPSTR, int ) ;

/************************************************************************
 * End of File: setup.h
 ************************************************************************/

