/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  APACHE, Apache For Windows
 *
 *      Module:  size.h
 *
 *   Author(s):  Bryan A. Woodruff (baw)
 *               Charles E. Kindel, Jr. (cek)
 *
 *
 *     Remarks:  Window sizing functions
 *
 *   Revisions:
 *     01.00.000  6/19/91 baw   Wrote it.
 *
 ************************************************************************/

// function prototypes (private)

BOOL SizeWindows( HWND, WORD, WORD ) ;

/************************************************************************
 * End of File: size.h
 ************************************************************************/

