//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WINPRINT.RC
//
#define IDR_PRINTER                     1
#define IDR_MAINFRAME                   2
#define IDS_INI_CONFIG                  3
#define IDS_INI_WNDPOS                  4
#define IDR_CONFIGFRAME                 5
#define IDR_CNTR_INPLACE                6
#define IDS_INI_SHOWCMD                 6
#define IDD_ABOUTBOX                    100
#define IDD_SPLASH                      103
#define IDD_PREFERENCES                 104
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDC_SIZEHORZ                    102
#define IDB_NA                          200
#define IDB_QUESTION                    201
#define IDB_PORTRAIT                    202
#define IDB_LANDSCAPE                   203
#define IDC_REGISTEREDTO                1000
#define IDC_BIGICON                     1008
#define ID_CANCEL_EDIT                  32768
#define ID_OPTIONS_PREFERENCES          32771
#define ID_FILE_NEWCONFIGURATION        32772
#define ID_FILE_NEWCONFIG               32773
#define ID_CONFIGURATION_EDIT           32774
#define ID_CONFIGURATION_PROPS          32775
#define ID_CONFIGURATION_REMOVE         32776
#define ID_CONFIGURATION_DELETE         32777
#define ID_CONFIGURATION_COPY           32778
#define ID_CONFIGURATION_SHOWICON       32779
#define ID_CONFIGURATION_CREATE         32780
#define ID_QUEUE_PAUSE                  32781
#define ID_QUEUE_MOVEUP                 32782
#define ID_QUEUE_MOVEDOWN               32783
#define ID_QUEUE_PAUSEITEM              32784
#define ID_QUEUE_DELETE                 32786
#define ID_SYS_SAVEMINPOS               32787
#define ID_SYS_ALWAYSONTOP              32789
#define ID_FILE_PRINTPREVIEW            32791
#define IDC_WINPRINT                    -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
