/************************************************************************
 *
 *     Copyright (c) 1992 Adonis Corporation.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *      Module:  dlgs.h
 *
 ***********************************************************************/

/* dialog boxes */

#define IDD_HELP                    8

#define IDD_LED1                 101
#define IDD_LED2                 102
#define IDD_LED3                 103
#define IDD_LED4                 104
#define IDD_LED5                 105
#define IDD_LED6                 106
#define IDD_LED7                 107
#define IDD_LED8                 108
#define IDD_LED9                 109
#define IDD_LED10                110
#define IDD_LED11                111
#define IDD_LED12                112
#define IDD_LED13                113
#define IDD_LED14                114
#define IDD_LED15                115
#define IDD_LED16                116
#define IDD_LED17                117
#define IDD_LED18                118
#define IDD_LED19                119
#define IDD_LED20                120


#define DLG_ABOUTBOX             1000

#define IDD_BOX0                 1001
#define IDD_APPNAME              1002
#define IDD_COPYRIGHT            1003
#define IDD_MSCOPYRIGHT          1004
#define IDD_BYCEK                1005
#define IDD_VERSION              1006


#define DLG_CONNECT              1200
#define IDD_MODEM                1201
#define IDD_PORT                 1202
#define IDD_BAUD                 1203
#define IDD_STATUS               1204
#define IDD_STARTTIME            1205
#define IDD_CURRENTTIME          1206




#define DLG_DISCONNECT              1300
#define DLG_ONLINE                  1400
#define IDD_LASTERROR               1401
#define IDD_NUMERRORS               1402
#define IDD_GASGAUGE                1403
#define IDD_FILENAME                1404
#define IDD_FILESIZE                1405
#define IDD_BYTECOUNT               1406
#define IDD_ESTTIME                 1407
#define IDD_THROUGHPUT              1408
#define IDD_FILEDOWNLOAD_GRP        1409

#define IDD_FILENAME_LBL            1504
#define IDD_FILESIZE_LBL            1505
#define IDD_BYTECOUNT_LBL           1506
#define IDD_ESTTIME_LBL             1507
#define IDD_THROUGHPUT_LBL          1508
