/************************************************************************
 *
 *     Copyright (c) 1992 Adonis Corporation.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *      Module:  modem.h
 *
 ***********************************************************************/

/*
 * Modem response defines
 */
#define MR_CONNECT         0x0000
#define MR_CONNECT300      0x0001
#define MR_CONNECT1200     0x0002
#define MR_CONNECT2400     0x0003
#define MR_CONNECT4800     0x0004
#define MR_CONNECT9600     0x0005
#define MR_BUSY            0x0006
#define MR_NODIALTONE      0x0007
#define MR_NOCARRIER       0x0008
#define MR_ERROR           0x0009

/************************************************************************
 * End of File: modem.h
 ***********************************************************************/

