/************************************************************************
 *
 *     Copyright (c) 1992 Adonis Corporation.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *      Module:  wndmgr.h
 *
 ***********************************************************************/

#ifndef _WNDMGR_H_
#define _WNDMGR_H_

LRESULT FAR PASCAL SizeHandler( HWND hWnd, WORD wMsg, WPARAM wParam, LPARAM lParam ) ;

#endif

/************************************************************************
 * End of File: wndmgr.h
 ***********************************************************************/

