/*************************************************************\
 ** FILE:  pref.c
 **
 ** Copyright (c) Adonis Corporation. 1990
 **
 ** DESCRIPTION:
 **
 ** HISTORY:   
 **   Lauren Bricker  May 25, 1990 (created)
 **
\*************************************************************/

/*-------------------------------------------------------------------------*/
/*                         G L O B A L   F U N C T I O N S                 */
/*-------------------------------------------------------------------------*/
LONG FAR PASCAL WSUpdateDBDlgProc (HWND hDlg, unsigned message, 
                                   WORD wParam, LONG lParam);
