/************************************************************************
 *
 *     Project:  
 *
 *      Module:  prtfile.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/
   WinPrtPrintFile( HWND hwndParent, 
                    LPSTR lpszDriver, LPSTR lpszDevice, LPSTR lpszPort,
                    LPDEVMODE lpDM, LPPAGEDESC lpPageDesc, LPSTR lpszFile ) ;



/************************************************************************
 * End of File: prtfile.h
 ***********************************************************************/

