#*************************************************************
#  
# MAKEFILE for stattest application
#
# Note this sample is protect mode only!!
#
#*************************************************************

#DEBUG=1

!IF "$(WIN32)"=="WIN32"

!include <ntwin32.mak>

   ###################################################
   #                                                 #
   #  Build STATTEST for Win32                       #
   #                                                 #
   ###################################################

stattest.exe:   stattest.obj\
                mustest.obj\
                stattest.def\
                stattest.res 
    $(link) $(guiflags) $(linkdebug) -out:stattest.exe mustest.obj stattest.obj stattest.res $(guilibs) cek32.lib wdb32.lib

stattest.obj: stattest.c resource.h
    $(cc) -DDEBUG $(cdebug) $(cflags) $(cvars) stattest.c > stattest.err
    $(cvtobj) stattest.obj

mustest.obj: mustest.c resource.h
    $(cc) -DDEBUG $(cdebug) $(cflags) $(cvars) stattest.c > mustest.err
    $(cvtobj) mustest.obj


stattest.res: stattest.rc stattest.ico stattest.dlg resource.h
    rc -r -fo stattest.tmp stattest.rc
    cvtres -$(CPU) stattest.tmp -o stattest.res
    del stattest.tmp

!else

   ###################################################
   #                                                 #
   #  Build STATTEST for Win16                       #
   #                                                 #
   ###################################################

MEM      =-AM

!ifdef DEBUG
LIBS     = wdb mlibcew cek
CLOPTS   =-f $(MEM) -c -G2sw -Owd -Zpei -W3 -DDEBUG
LINKOPTS =/NOD/NOE/CO
!else
LIBS     =mlibcew cek
CLOPTS   =$(MEM) -c -G2sw -Owt -Zp -W3 
LINKOPTS =/NOD/NOE
!endif

stattest.exe:   stattest.obj\
                mustest.obj\
                stattest.def\
                stattest.res 
    link $(LINKOPTS) stattest mustest,,,$(LIBS) libw, stattest.def
    rc -v -30 stattest.res

stattest.obj: stattest.c resource.h
    cl $(CLOPTS) stattest.c > stattest.err

mustest.obj: mustest.c resource.h
    cl $(CLOPTS) mustest.c > mustest.err

stattest.res: stattest.rc stattest.ico stattest.dlg resource.h
    rc -r stattest.rc

!endif

