/************************************************************************
 *
 *     Copyright (c) 1992 Charles E. Kindel, Jr.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *      Module:  dlgs.h
 *
 ***********************************************************************/

/* dialog boxes */

#define IDD_HELP                    8

#define DLG_ABOUTBOX             1000

#define IDD_BOX0                 1001
#define IDD_APPNAME              1002
#define IDD_COPYRIGHT            1003
#define IDD_MSCOPYRIGHT          1004
#define IDD_BYCEK                1005
#define IDD_VERSION              1006


