//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WINPRT20.RC
//
#define IDS_WINPRINTENGINE              1
#define IDB_WINPRINTENGINE              1
#define IDB_WINPRINTCONTROL             2
#define IDS_WINPRINTCONTROL             3
#define IDS_WINPRINTCONTROL_PPG         4
#define IDI_ABOUTDLL                    10
#define IDD_ABOUTBOX_WINPRINTENGINE     100
#define IDD_ABOUTBOX_WINPRINTCONTROL    102
#define IDS_WINPRINTCONTROL_PPG_CAPTION 103
#define IDD_PROPPAGE_WINPRINTCONTROL    103
#define IDI_WINPRINT                    105
#define IDI_LANDSCAPE                   106
#define IDI_NOORIENT                    107
#define IDI_PORTRAIT                    108
#define IDS_PROPERTIESVERB              200
#define IDS_CONFIGFILENAME              201
#define IDC_CONFIGNAME                  202
#define IDC_PRINTER_TXT                 203
#define IDC_FILETYPEDRV_TXT             204
#define IDC_SHADE                       205
#define IDC_HEADERS                     206
#define IDC_PORTRAIT                    207
#define IDC_BORDER                      208
#define IDC_PRINTERDEV_TXT              209
#define IDC_PRINTER                     210
#define IDC_LANDSCAPE                   211
#define IDC_LEFT                        212
#define IDC_RIGHT                       213
#define IDC_TOP                         214
#define IDC_BOTTOM                      215
#define IDC_PRINTEROUT_TXT              216
#define IDC_DEFAULTPRN                  217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         218
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
