// stdafx.h : include file for standard system include files,
//      or project specific include files that are used frequently,
//      but are changed infrequently

#include <afxwin.h>         // MFC core and standard components
#include <afxole.h>         // MFC support for OLE 2.0
#include <afxctl.h>         // MFC support for OLE Custom Controls
                                            
#include <windowsx.h>
                                            
#define UNUSED  // usage : UNUSED formal-arg