//***************************************************************************
//
//  Module: precomp.h
//
//  Purpose:
//     Header file of all stable precompiled garbage.
//
//  Development Team:
//     Bryan A. Woodruff
//
//  History:   Date       Author      Comment
//              1/25/92   BryanW      Moved from TASKPRIV.H
//
//
//---------------------------------------------------------------------------
//
//  *** ***  THIS CODE IS CONFIDENTIAL PROPERTY OF WERNER ASSOCIATES *** *** 
//  Copyright (c) 1992 Werner Associates.  All Rights Reserved.
//
//***************************************************************************

#define _WINDLL            // we're in a DLL
#define STRICT             // be bold!

#include <windows.h>
#include <wdb.h>

//***************************************************************************
//  End of File: precomp.h
//***************************************************************************

