 /* cmnd.h               (c) KindelCo Software Systems, 1987

                      COMMAND - Command loop definitions (Cm)

Author:   Charles E. Kindel, Jr. (tigger)

Started:  July 22, 1987
Version:  1.00


DIRECTORY
Cmnd ()         The command loop.
CmWrit ()       Writes the buffer.
CmVers ()       Prints version number, repaints screen
Cmatoi ()       string to integer
Cmltoa ()       long to string
CmGoLin ()      Move to a line #.


*/

void Cmnd ();
void CmWrit ();
void CmVers ();


/*==========================================================================*/
/*    END OF  cmnd.c              (C) KindelCo Software Systems, 1987       */
/*==========================================================================*/
