//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by INIEDIT.RC
//
#define IDR_MAINFRAME                   2
#define IDR_INITYPE                     3
#define IDR_FILESTYPE                   4
#define IDS_INIFILESPEC                 5
#define IDS_INI_OTHERFILES              6
#define IDD_ABOUTBOX                    100
#define IDC_FILELIST                    101
#define IDD_FILELIST                    101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         102
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
