//***************************************************************************
//
//  Module: precomp.h
//
//  Purpose:
//     This header contains all of the precompiled garbage.
//
//  Development Team:
//     Bryan A. Woodruff
//
//  History:   Date       Author      Comment
//              1/26/92   BryanW      Wrote it.
//
//---------------------------------------------------------------------------
//
//  *** ***  THIS CODE IS CONFIDENTIAL PROPERTY OF WERNER ASSOCIATES *** *** 
//  Copyright (c) 1992 Werner Associates.  All Rights Reserved.
//
//***************************************************************************

#define _WINDLL            // we're in a DLL
#define STRICT             // be bold!
#define USECOMM            // use communications stuff

#include <windows.h>
#include <wdb.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

//***************************************************************************
//  End of File: precomp.h
//***************************************************************************

