
{
   Finds the directory for data files by reading the environment variable
   named LOOP_FILES.  To get this program to write it's output to the
   C:\PASCAL\BEES directory make sure that an environment variable named
   LOOP_FILESis set equal to 'C:\PASCAL\LOOPS'.  This can be done by typing
   SET LOOP_FILES=C:\PASCAL\LOOPS at the DOS prompt.  This string is put in the
   variable "defaultpath".  6/7/1988 CE Kindel.
}

