
{
   Finds the directory for data files by reading the environment variable
   named ENV_FILES.  To get this program to write it's output to the
   C:\PASCAL\BEES directory make sure that an environment variable named
   ENV_FILES is set equal to 'C:\PASCAL\BEES'.  This can be done by typing
   SET ENV_FILES=C:\PASCAL\BEES at the DOS prompt.  This string is put in the
   variable "defaultpath".  6/7/1988 CE Kindel.
}
