

  Procedure KindlCo;
    begin
      Writeln (Center ('лл    лл  лллл  ллл     лл  ллллллл   лл       лллллл    лллллл ',79));
      Writeln (Center ('лл   лл    лл   лллл    лл  лл    лл  лл      лл    лл  лл    лл',79));
      Writeln (Center ('лл  лл     лл   лл лл   лл  лл    лл  лл      лл        лл    лл',79));
      Writeln (Center ('ллллл      лл   лл  лл  лл  лл    лл  лл      лл        лл    лл',79));
      Writeln (Center ('лл  лл     лл   лл   лл лл  лл    лл  лл      лл        лл    лл',79));
      Writeln (Center ('лл   лл    лл   лл    лллл  лл    лл  лл      лл    лл  лл    лл',79));
      Writeln (Center ('лл    лл  лллл  лл     ллл  ллллллл   ллллллл  лллллл    лллллл ',79));
      Writeln (Center ('Software Systems',79)) ;
      Writeln (Center ('Copyright (C) 1986-'+Long2Str(Year)+' Charles E. Kindel, Jr.',79));
    end;
