/************************************************************************
 *
 *     Project:  
 *
 *      Module:  cmd.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/
#ifndef _CMD_H_
#define _CMD_H_

/* NOTE!  Remember that the toolbar bitmaps use these ID's, and IDSs */
/* defined in toolbar.h */


#define IDM_FILE                       0
#define IDM_FILE_OPEN                  1
#define IDM_FILE_COMMIT                2
#define IDM_FILE_EDIT                  3
#define IDM_FILE_PRINTSETUP            4
#define IDM_FILE_PRINT                 5
#define IDM_FILE_EXIT                  6

#define IDM_EDIT                       7
#define IDM_EDIT_COPY                  8
#define IDM_EDIT_COPY_FILE             9
#define IDM_EDIT_COPY_SECTION          10
#define IDM_EDIT_COPY_KEYVALUE         11
#define IDM_EDIT_COPY_KEY              12
#define IDM_EDIT_COPY_VALUE            13
#define IDM_EDIT_PASTE                 14
#define IDM_EDIT_UNDO                  15
#define IDM_EDIT_ADD                   16
#define IDM_EDIT_ADD_FILE              17
#define IDM_EDIT_ADD_SECTION           18
#define IDM_EDIT_ADD_KEY               19
#define IDM_EDIT_DEL                   20
#define IDM_EDIT_DEL_FILE              21
#define IDM_EDIT_DEL_SECTION           22
#define IDM_EDIT_DEL_KEY               23

#define IDM_SEARCH                     24
#define IDM_SEARCH_FIND                25
#define IDM_SEARCH_FINDNEXT            26
#define IDM_SEARCH_REPLACE             27
#define IDM_SEARCH_ALL                 28

#define IDM_OPT                        29
#define IDM_OPT_FONT                   30
#define IDM_OPT_EDITOR                 31
#define IDM_OPT_TOOLBAR                32
#define IDM_OPT_TOOLBARLABELS          33
#define IDM_OPT_STAT                   34

#define IDM_HELP                       35
#define IDM_HELP_CONTENTS              36 
#define IDM_HELP_CURRENT               37 
#define IDM_HELP_SEARCH                38 
#define IDM_HELP_ONHELP                39 
#define IDM_HELP_ABOUT                 40 


#define IDM_FILE_DN                    100
#define IDM_FILE_OPEN_DN               101
#define IDM_FILE_COMMIT_DN             102
#define IDM_FILE_EDIT_DN               103
#define IDM_FILE_PRINTSETUP_DN         104
#define IDM_FILE_PRINT_DN              105
#define IDM_FILE_EXIT_DN               106

#define IDM_EDIT_DN                    107
#define IDM_EDIT_COPY_DN               108
#define IDM_EDIT_COPY_FILE_DN          109
#define IDM_EDIT_COPY_SECTION_DN       110
#define IDM_EDIT_COPY_KEYVALUE_DN      111
#define IDM_EDIT_COPY_KEY_DN           112
#define IDM_EDIT_COPY_VALUE_DN         113
#define IDM_EDIT_PASTE_DN              114
#define IDM_EDIT_UNDO_DN               115
#define IDM_EDIT_ADD_DN                116
#define IDM_EDIT_ADD_FILE_DN           117
#define IDM_EDIT_ADD_SECTION_DN        118
#define IDM_EDIT_ADD_KEY_DN            119
#define IDM_EDIT_DEL_DN                120
#define IDM_EDIT_DEL_FILE_DN           121
#define IDM_EDIT_DEL_SECTION_DN        122
#define IDM_EDIT_DEL_KEY_DN            123

#define IDM_SEARCH_DN                  124
#define IDM_SEARCH_FIND_DN             125
#define IDM_SEARCH_FINDNEXT_DN         126
#define IDM_SEARCH_REPLACE_DN          127
#define IDM_SEARCH_ALL_DN              128

#define IDM_OPT_DN                     129
#define IDM_OPT_FONT_DN                130
#define IDM_OPT_EDITOR_DN              131
#define IDM_OPT_TOOLBAR_DN             132
#define IDM_OPT_TOOLBARLABELS_DN       133
#define IDM_OPT_STAT_DN                134

#define IDM_HELP_DN                    135
#define IDM_HELP_CONTENTS_DN           136
#define IDM_HELP_CURRENT_DN            137
#define IDM_HELP_SEARCH_DN             138
#define IDM_HELP_ONHELP_DN             139
#define IDM_HELP_ABOUT_DN              140


#define IDM_FILE_S                     200
#define IDM_FILE_OPEN_S                201
#define IDM_FILE_COMMIT_S              202
#define IDM_FILE_EDIT_S                203
#define IDM_FILE_PRINTSETUP_S          204
#define IDM_FILE_PRINT_S               205
#define IDM_FILE_EXIT_S                206

#define IDM_EDIT_S                     207
#define IDM_EDIT_COPY_S                208
#define IDM_EDIT_COPY_FILE_S           209
#define IDM_EDIT_COPY_SECTION_S        210
#define IDM_EDIT_COPY_KEYVALUE_S       211
#define IDM_EDIT_COPY_KEY_S            212
#define IDM_EDIT_COPY_VALUE_S          213
#define IDM_EDIT_PASTE_S               214
#define IDM_EDIT_UNDO_S                215
#define IDM_EDIT_ADD_S                 216
#define IDM_EDIT_ADD_FILE_S            217
#define IDM_EDIT_ADD_SECTION_S         218
#define IDM_EDIT_ADD_KEY_S             219
#define IDM_EDIT_DEL_S                 220
#define IDM_EDIT_DEL_FILE_S            221
#define IDM_EDIT_DEL_SECTION_S         222
#define IDM_EDIT_DEL_KEY_S             223
                                        
#define IDM_SEARCH_S                   224
#define IDM_SEARCH_FIND_S              225
#define IDM_SEARCH_FINDNEXT_S          226
#define IDM_SEARCH_REPLACE_S           227
#define IDM_SEARCH_ALL_S               228
                                        
#define IDM_OPT_S                      229
#define IDM_OPT_FONT_S                 230
#define IDM_OPT_EDITOR_S               231
#define IDM_OPT_TOOLBAR_S              232
#define IDM_OPT_TOOLBARLABELS_S        233
#define IDM_OPT_STAT_S                 234

#define IDM_HELP_S                     235
#define IDM_HELP_CONTENTS_S            236
#define IDM_HELP_CURRENT_S             237
#define IDM_HELP_SEARCH_S              238
#define IDM_HELP_ONHELP_S              239
#define IDM_HELP_ABOUT_S               240

#define IDM_FILE_S_DN                  300
#define IDM_FILE_OPEN_S_DN             301
#define IDM_FILE_COMMIT_S_DN           302
#define IDM_FILE_EDIT_S_DN             303
#define IDM_FILE_PRINTSETUP_S_DN       304
#define IDM_FILE_PRINT_S_DN            305
#define IDM_FILE_EXIT_S_DN             306

#define IDM_EDIT_S_DN                  307
#define IDM_EDIT_COPY_S_DN             308
#define IDM_EDIT_COPY_FILE_S_DN        309
#define IDM_EDIT_COPY_SECTION_S_DN     310
#define IDM_EDIT_COPY_KEYVALUE_S_DN    311
#define IDM_EDIT_COPY_KEY_S_DN         312
#define IDM_EDIT_COPY_VALUE_S_DN       313
#define IDM_EDIT_PASTE_S_DN            314
#define IDM_EDIT_UNDO_S_DN             315
#define IDM_EDIT_ADD_S_DN              316
#define IDM_EDIT_ADD_FILE_S_DN         317
#define IDM_EDIT_ADD_SECTION_S_DN      318
#define IDM_EDIT_ADD_KEY_S_DN          319
#define IDM_EDIT_DEL_S_DN              320
#define IDM_EDIT_DEL_FILE_S_DN         321
#define IDM_EDIT_DEL_SECTION_S_DN      322
#define IDM_EDIT_DEL_KEY_S_DN          323

#define IDM_SEARCH_S_DN                324
#define IDM_SEARCH_FIND_S_DN           325
#define IDM_SEARCH_FINDNEXT_S_DN       326
#define IDM_SEARCH_REPLACE_S_DN        327
#define IDM_SEARCH_ALL_S_DN            328

#define IDM_OPT_S_DN                   329
#define IDM_OPT_FONT_S_DN              330
#define IDM_OPT_EDITOR_S_DN            331
#define IDM_OPT_TOOLBAR_S_DN           332
#define IDM_OPT_TOOLBARLABELS_S_DN     333
#define IDM_OPT_STAT_S_DN              334

#define IDM_HELP_S_DN                  335
#define IDM_HELP_CONTENTS_S_DN         336
#define IDM_HELP_CURRENT_S_DN          337
#define IDM_HELP_SEARCH_S_DN           338
#define IDM_HELP_ONHELP_S_DN           339
#define IDM_HELP_ABOUT_S_DN            340

#define IDCHILD_LISTBOX  512
#define IDCHILD_STAT     513
#define IDCHILD_TOOLBAR  514
#define IDCHILD_INPUT    515


LRESULT WINAPI CmdHandler( HWND hWnd, WORD wMsg, WPARAM wParam, LPARAM lParam ) ;
LRESULT WINAPI SysCmdHandler( HWND hWnd, WORD wMsg, WPARAM wParam, LPARAM lParam ) ;

void WINAPI UpdateInfo( void ) ;

#endif

/************************************************************************
 * End of File: cmd.h
 ***********************************************************************/

