/************************************************************************
 *
 *      Module:  input.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ************************************************************************/
#ifndef _INPUT_H_
#define _INPUT_H_

#define  SZ_INPUTCLASSNAME  "INI_input"
HWND FAR PASCAL CreateInput( HWND hwndParent ) ;

#endif

/************************************************************************
 * End of File: input.h
 ************************************************************************/

