/************************************************************************
 *
 *     Project:  INIEDIT 2.0
 *
 *      Module:  res.h
 *
 *     Remarks:  Resource defines
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/
#ifndef _RES_H_
#define _RES_H_

#define IDI_INIEDIT        1

#define IDB_LISTBOXICONS   2048

#define ID_RCDATA_ORDER_FRM   1
#endif

/************************************************************************
 * End of File: res.h
 ***********************************************************************/

