//***************************************************************************
//
//  Module: precomp.h
//
//  Purpose:
//     This header contains all of the precompiled garbage.
//
//***************************************************************************

#ifndef WIN32
#define STRICT             // be bold!
#endif

#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <cderr.h>      // commdlg errors
#include <ddeml.h>

#include <io.h>
#include <direct.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys\types.h>
#include <sys\stat.h>         // time shit
#include <string.h>
#include <time.h>
#include <memory.h>

#include "wdb.h"

//***************************************************************************
//  End of File: precomp.h
//***************************************************************************

