#define IDM_HELPABOUT 100
#define IDM_FILEOPEN 101
#define IDM_FILEEXIT 102
#define IDM_MSGBOTTOM 103
#define IDM_MSGVISIBLE 104
#define IDM_NEXTMSG 105
#define IDM_SELPRN 106
#define IDM_SELFONT 107

#define IDM_RASTER   256
#define IDM_DEVICE   257
#define IDM_ANSI     258
#define IDM_SYMBOL   259
#define IDM_SHIFTJIS 260
#define IDM_OEM      261
#define IDM_VARIABLE 262
#define IDM_FIXED    263

#define IDM_DEFAULT  270

#define IDM_USEPRINTER  280
#define IDM_NOPRINTER   281
#define IDM_NOFGCOLOR   282
#define IDM_NOBGCOLOR   283
#define IDM_NODEFAULT   284
#define IDM_NOBOLD      285
#define IDM_NOITALIC    286
#define IDM_NOUNDERLINE 287
#define IDM_NOSTRIKEOUT 288

#define IDM_PRINT       300
#define IDM_LED       301
#define IDM_TEST       302

#define IDD_TOP      500
#define IDD_BOTTOM   501
#define IDD_BOX0     200
#define IDD_BOX1     201
#define IDD_DESC     250

#define IDB_BEGIN    1024
#define IDB_1        IDB_BEGIN
#define IDB_2        1 + IDB_1
#define IDB_3        2 + IDB_1
#define IDB_END      IDB_3
#define IDB_4        3 + IDB_1

#define IDB_5        4 + IDB_1
#define IDB_6        5 + IDB_1
#define IDB_7        6 + IDB_1
#define IDB_8        7 + IDB_1

#define IDB_9        8 + IDB_1
#define IDB_10       9 + IDB_1
#define IDB_11       10 + IDB_1
#define IDB_12       11 + IDB_1
#define IDB_13       12 + IDB_1
#define IDB_14       13 + IDB_1
#define IDB_15       14 + IDB_1
#define IDB_16       15 + IDB_1

#define  IDS_APPNAME 2048
#define  IDS_HEXFMT  2049
#define  IDS_LPSTRFMT 2050



