//***************************************************************************
//
//  Module: precomp.h
//
//  Purpose:
//     This header contains all of the precompiled garbage.
//
//  Development Team:
//     Bryan A. Woodruff
//
//  History:   Date       Author      Comment
//              1/26/92   BryanW      Wrote it.
//
//***************************************************************************

#define _WINDLL            // we're in a DLL
#define STRICT             // be bold!

#include <windows.h>
#include <windowsx.h>
#include <io.h>
#include <direct.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "..\..\inc\wdb.h"

//***************************************************************************
//  End of File: precomp.h
//***************************************************************************


