#define ZM_GET_BLOCKCOUNT        0x8001
#define ZM_GET_BLOCKSIZE         0x8002
#define ZM_GET_CANCOUNT          0x8003
#define ZM_GET_CHARCOUNT         0x8004
#define ZM_GET_CONSECERRORS      0x8005
#define ZM_GET_CRCTYPE           0x8006
#define ZM_GET_CURFILE           0x8007
#define ZM_GET_FILEBYTES         0x8008
#define ZM_GET_FILEDATE          0x8009
#define ZM_GET_FILENAME          0x800a
#define ZM_GET_FILESIZE          0x800b
#define ZM_GET_FILETIME          0x800c
#define ZM_GET_INCOMINGCOUNT     0x800d
#define ZM_GET_INCOMINGPOS       0x800e
#define ZM_GET_LASTERROR         0x800f
#define ZM_GET_LENGTH            0x8010
#define ZM_GET_MAXERRORS         0x8011
#define ZM_GET_OUTCOUNT          0x8012
#define ZM_GET_POSITION          0x8013
#define ZM_GET_RECEIVED          0x8014
#define ZM_GET_TIMEREAD          0x8015
#define ZM_GET_TIMESTARTED       0x8016
#define ZM_GET_TOTALBLOCKS       0x8017
#define ZM_GET_TOTALERRORS       0x8018
#define ZM_GET_TOTALFILES        0x8019
#define ZM_GET_TRANSMITTED       0x801a

#define ZMODEMDLGBOX                100

#define DLG_STATUS                  101

#define IDD_DLGFRAME1               0x100

#define IDD_FILENAME                0x200
#define IDD_FILESIZE                0x201
#define IDD_CRCTYPE                 0x202
#define IDD_TOTALBLOCKS             0x203
#define IDD_TIMEESTIMATE            0x204
#define IDD_RECEIVED                0x205
#define IDD_BYTECOUNT               0x206
#define IDD_BLOCKCOUNT              0x207
#define IDD_CORRECTIONS             0x208
#define IDD_AVERAGECPS              0x209
#define IDD_LASTMESSAGE             0x20A
#define IDD_PROGRESS                0x20B

