/*****************************************************************************\
*                                                                             *
*  Copyright (c) 1989 Werner Associates.  All Rights Reserved.                *
*                                                                             *
*  Project:   XTALK, Crosstalk for Windows.                                   *
*                                                                             *
*  Program:   Resource Generator (RESOURCE.C)                                 *
*                                                                             *
*   Author:   Kent David Cedola.                                              *
*                                                                             *
*   System:   Microsoft Windows 2.1d, Microsoft Windows 386 2.1d under        *
*             DOS 3.3 and compiled with Microsoft C 5.1.                      *
*                                                                             *
*  Remarks:   We store the keywords for the tokenizer in a data resource that *
*             be discarded to save some memory.  This program generates that  *
*             file.                                                           *
*                                                                             *
*  Revisions: 1.00 07/17/89 Initial Version.                                  *
*                                                                             *
\*****************************************************************************/

#include <stdio.h>

#define BOOL
#define BYTE    unsigned char
#define far
#define pascal
#define LPSTR
#define HANDLE

#include "compile.h"

typedef struct
  {
  char	   name[32];
  unsigned value;
  } TOKEN;

TOKEN tokens[] =
  {
  "ABS",		TK_ABS,
  "ACTIVATE",		TK_ACTIVATE,
  "ACTIVE",		TK_ACTIVE,
  "ACTIVITY",		TK_ACTIVITY,
  "ADD",		TK_ADD,
  "ALARM",		TK_ALARM,
  "ALERT",		TK_ALERT,
  "ALTNUMS",		TK_ALTNUMS,
  "AND",		TK_AND,
  "ANSWER",		TK_ANSWER,
  "ANSWERBACK", 	TK_ANSWERBACK,
  "ANSWERSETUP",	TK_ANSWERSETUP,
  "APPEND",		TK_APPEND,
  "ARG",		TK_ARG,
  "AS", 		TK_AS,
  "ASC",		TK_ASC,
  "ASSUME",		TK_ASSUME,
  "AT", 		TK_AT,
  "ATTACH",		TK_ATTACH,
  "ATTEN",		TK_ATTEN,
  "AUTOWRAP",		TK_AUTOWRAP,
  "BACKUPS",		TK_BACKUPS,
  "BINARY",		TK_BINARY,
  "BITSTRIP",           TK_BITSTRIP,
  "BLOCKSIZE",          TK_BLOCKSIZE,
  "BLANKEX",		TK_BLANKEX,
  "BOL",                TK_BOL,
  "BOOKNAME",		TK_BOOKNAME,
  "BOW",                TK_BOW,
  "BREAKLEN",		TK_BREAKLEN,
  "BYE",		TK_BYE,
  "CALL",		TK_CALL,
  "CANCEL",             TK_CANCEL,
  "CAPACITY",		TK_CAPACITY,
  "CAPCHARS",		TK_CAPCHARS,
  "CAPFILE",		TK_CAPFILE,
  "CAPTURE",		TK_CAPTURE,
  "CASE",		TK_CASE,
  "CHAIN",		TK_CHAIN,
  "CHDIR",		TK_CHDIR,
  "CHECKBOX",           TK_CHECKBOX,
  "CHMOD",		TK_CHMOD,
  "CHOICE",             TK_CHOICE,
  "CHR",		TK_CHR,
  "CKSUM",		TK_CKSUM,
  "CLASS",		TK_CLASS,
  "CLEAR",		TK_CLEAR,
  "CLOSE",		TK_CLOSE,
  "CLS",		TK_CLS,
  "CMODE",		TK_CMODE,
  "CODESAVE",           TK_CODESAVE,
  "COLORSCREEN",	TK_COLORSCREEN,
  "COLUMNS",		TK_COLUMNS,
  "COMPILE",		TK_COMPILE,
  "CONNECTARQ", 	TK_CONNECTARQ,
  "CONNECTED",		TK_CONNECTED,
  "CONNECTSPEED",	TK_CONNECTSPEED,
  "COPY",		TK_COPY,
  "COUNT",		TK_COUNT,
  "CPM",                TK_CPM,
  "CRC",		TK_CRC,
  "CRN",		TK_CRN,
  "CTEXT",              TK_CTEXT,
  "CURDAY",		TK_CURDAY,
  "CURDIR",		TK_CURDIR,
  "CURDRIVE",		TK_CURDRIVE,
  "CURHOUR",		TK_CURHOUR,
  "CURMINUTE",		TK_CURMINUTE,
  "CURMONTH",		TK_CURMONTH,
  "CURSECOND",		TK_CURSECOND,
  "CURSHAPE",		TK_CURSHAPE,
  "CURYEAR",		TK_CURYEAR,
  "CWAIT",		TK_CWAIT,
  "DATABITS",		TK_DATABITS,
  "DATE",               TK_DATE,
  "DATEMODE",           TK_DATEMODE,
  "DAYNO",		TK_DAYNO,
  "DDE",		TK_DDE,
  "DDEEXECUTE", 	TK_DDEEXECUTE,
  "DDEINITIATE",	TK_DDEINITIATE,
  "DDEPOKE",		TK_DDEPOKE,
  "DDEREQUEST", 	TK_DDEREQUEST,
  "DDESTATUS",		TK_DDESTATUS,
  "DDETERMINATE",	TK_DDETERMINATE,
  "DECRYPT",		TK_DECRYPT,
  "DEFINPUT",		TK_DEFINPUT,
  "DEFOUTPUT",		TK_DEFOUTPUT,
  "DEFPUSHBUTTON",      TK_DEFPUSHBUTTON,
  "DEHEX",		TK_DEHEX,
  "DELAY",              TK_DELAY,
  "DELETE",		TK_DELETE,
  "DESCRIPTION",	TK_DESCRIPTION,
  "DESTORE",		TK_DESTORE,
  "DETEXT",		TK_DETEXT,
  "DIAL",		TK_DIAL,
  "DIALOGBOX",          TK_DIALOGBOX,
  "DIALPREFIX", 	TK_DIALPREFIX,
  "DIALSUFFIX", 	TK_DIALSUFFIX,
  "DISKSPACE",		TK_DISKSPACE,
  "DISPLAY",		TK_DISPLAY,
  "DO", 		TK_DO,
  "DOS",                TK_DOS,
  "DOSVERSION", 	TK_DOSVERSION,
  "DRIVE",		TK_DRIVE,
  "ECHO",		TK_ECHO,
  "EDIT",		TK_EDIT,
  "EDITOR",             TK_EDITOR,
  "EDITTEXT",           TK_EDITTEXT,
  "ELSE",		TK_ELSE,
  "ENCRYPT",		TK_ENCRYPT,
  "END",		TK_END,
  "ENDDIALOG",          TK_ENDDIALOG,
  "ENDWATCH",		TK_ENDWATCH,
  "ENHEX",		TK_ENHEX,
  "ENSTORE",		TK_ENSTORE,
  "ENTER",		TK_ENTER,
  "ENTEXT",		TK_ENTEXT,
  "ENVIRON",		TK_ENVIRON,
  "EOF",		TK_EOF,
  "EOL",		TK_EOL,
  "EOW",                TK_EOW,
  "ERRCLASS",		TK_ERRCLASS,
  "ERRNO",		TK_ERRNO,
  "ERROR",		TK_ERROR,
  "EXCODE",		TK_EXCODE,
  "EXISTS",		TK_EXISTS,
  "EXIT",		TK_EXIT,
  "EXTRACT",		TK_EXTRACT,
  "FALSE",		TK_FALSE,
  "FILEATTR",		TK_FILEATTR,
  "FILEDATE",		TK_FILEDATE,
  "FILEFIND",		TK_FILEFIND,
  "FILESIZE",		TK_FILESIZE,
  "FILETIME",		TK_FILETIME,
  "FKEY",		TK_FKEY,
  "FLISTCOUNT",         TK_FLISTCOUNT,
  "FLISTNAME",          TK_FLISTNAME,
  "FLOW",		TK_FLOW,
  "FNCHECK",		TK_FNCHECK,
  "FNSTRIP",		TK_FNSTRIP,
  "FOOTER",		TK_FOOTER,
  "FOCUS",              TK_FOCUS,
  "FOR",		TK_FOR,
  "FORMFEED",		TK_FORMFEED,
  "FRAMINGERRORS",	TK_FRAMINGERRORS,
  "FREEFILE",		TK_FREEFILE,
  "FREEMEM",		TK_FREEMEM,
  "GET",		TK_GET,
  "GLOBAL",		TK_GLOBAL,
  "GO", 		TK_GO,
  "GOSUB",		TK_GOSUB,
  "GOTO",		TK_GOTO,
  "GRAB",		TK_GRAB,
  "GRAPHICS",		TK_GRAPHICS,
  "GROUP",              TK_GROUP,
  "GROUPBOX",           TK_GROUPBOX,
  "HALT",		TK_HALT,
  "HEADER",		TK_HEADER,
  "HEX",		TK_HEX,
  "HIDE",		TK_HIDE,
  "HMS",		TK_HMS,
  "HOSTSCRIPT",         TK_HOSTSCRIPT,
  "HOSTMODE",		TK_HOSTMODE,
  "HOUR",		TK_HOUR,
  "HOURS",		TK_HOUR,
  "IF", 		TK_IF,
  "INBOOK",		TK_INBOOK,
  "INCLUDE",		TK_INCLUDE,
  "INDEX",		TK_INDEX,
  "INJECT",		TK_INJECT,
  "INKEY",		TK_INKEY,
  "INP",		TK_INP,
  "INPUT",		TK_INPUT,
  "INSCRIPT",		TK_INSCRIPT,
  "INSERT",		TK_INSERT,
  "INSTR",		TK_INSTR,
  "INTEGER",		TK_INTEGERKEY,
  "INTVAL",             TK_INTVAL,
  "IS", 		TK_EQ,
  "ISNT",		TK_INEQ,
  "JUMP",		TK_GOTO,
  "KBFLAGS",		TK_KBFLAGS,
  "KCLEAR",             TK_KCLEAR,
  "KERMIT",		TK_KERMIT,
  "KEY",		TK_KEY,
  "LABEL",		TK_LABEL,
  "LDNUMBER",		TK_LDNUMBER,
  "LEFT",		TK_LEFT,
  "LENGTH",		TK_LENGTH,
  "LFAUTO",		TK_LFAUTO,
  "LINE",		TK_LINE,
  "LINEDELIM",		TK_LINEDELIM,
  "LINETIME",		TK_LINETIME,
  "LISTBOX",            TK_LISTBOX,
  "LOAD",		TK_LOAD,
  "LOC",		TK_LOC,
  "LOCAL",		TK_LOCAL,
  "LOG",		TK_LOG,
  "LOWCASE",		TK_LOWCASE,
  "LPRINT",		TK_LPRINT,
  "LTEXT",              TK_LTEXT,
  "LWAIT",		TK_LWAIT,
  "MANUAL",             TK_MANUAL,
  "MATCH",		TK_MATCH,
  "MAX",		TK_MAX,
  "MAXERRORS",          TK_MAXERRORS,
  "MAXIMIZE",		TK_MAXIMIZE,
  "MESSAGE",		TK_MESSAGE,
  "MID",		TK_MID,
  "MILLISECOND",	TK_MILLISEC,
  "MILLISECONDS",	TK_MILLISEC,
  "MIN",		TK_MIN,
  "MINIMIZE",		TK_MINIMIZE,
  "MINUS",		TK_SUB,
  "MINUTE",		TK_MINUTE,
  "MINUTES",		TK_MINUTE,
  "MISC",		TK_MISC,
  "MKDIR",		TK_MKDIR,
  "MKINT",		TK_MKINT,
  "MKSTR",		TK_MKSTR,
  "MOD",		TK_MOD,
  "MODEMCHANGE",	TK_MODEMCHANGE,
  "MODEMHANGUP",	TK_MODEMHANGUP,
  "MODEMNAME",		TK_MODEMNAME,
  "MODEMINIT",		TK_MODEMINIT,
  "MODEMRESULTS",	TK_MODEMRESULTS,
  "MODIFIED",		TK_MODIFIED,
  "MODIFIER",		TK_MODIFIER,
  "MOVE",               TK_MOVE,
  "MSEC",               TK_MILLISEC,
  "NAME",		TK_NAME,
  "NETID",		TK_NETID,
  "NEW",		TK_NEW,
  "NEWLINE",		TK_NEWLINE,
  "NEXTCHAR",		TK_NEXTCHAR,
  "NEXTLINE",		TK_NEXTLINE,
  "NOCOLOR",		TK_NOCOLOR,
  "NONE",               TK_NONE,
  "NORMAL",             TK_NORMAL,
  "NOT",		TK_NOT,
  "NULL",		TK_NULL,
  "NUMBER",		TK_NUMBER,
  "OCTAL",		TK_OCTAL,
  "OFF",		TK_OFF,
  "OK",                 TK_OK,
  "ON", 		TK_ON,
  "ONLINE",		TK_ONLINE,
  "ONTIME",		TK_ONTIME,
  "OPEN",		TK_OPEN,
  "OR", 		TK_OR,
  "OUT",		TK_OUT,
  "OUTNUMBER",		TK_OUTNUMBER,
  "OUTPUT",		TK_OUTPUT,
  "OVER",		TK_DIV,
  "OVERRUNERRORS",	TK_OVERRUNERRORS,
  "PACK",               TK_PACK,
  "PACKETSIZE",         TK_PACKETSIZE,
  "PAD",		TK_PAD,
  "PAN",                TK_PAN,
  "PARENT",		TK_PARENT,
  "PARITY",		TK_PARITY,
  "PARITYERRORS",	TK_PARITYERRORS,
  "PASSWORD",		TK_PASSWORD,
  "PATIENCE",		TK_PATIENCE,
  "PAUSE",              TK_PAUSE,
  "PERFORM",            TK_PERFORM,
  "PLUS",               TK_PLUS,
  "PMODE",              TK_PMODE,
  "PORT",		TK_PORT,
  "POP",		TK_POP,
  "PRESS",              TK_PRESS,
  "PRINT",		TK_PRINT,
  "PRINTER",		TK_PRINTER,
  "PRINTEXTENT",	TK_PRINTEXTENT,
  "PROMPT",             TK_PROMPT,
  "PROTOCOL",		TK_PROTOCOL,
  "PUSHBUTTON",         TK_PUSHBUTTON,
  "PUT",		TK_PUT,
  "QUIET",		TK_QUIET,
  "QUIT",		TK_QUIT,
  "QUOTE",		TK_QUOTE,
  "RADIOBUTTON",        TK_RADIOBUTTON,
  "RANDOM",		TK_RANDOM,
  "RAW",                TK_RAW,
  "READ",		TK_READ,
  "RECEIVE",            TK_RECEIVE,
  "RECOVERY",           TK_RECOVERY,
  "RECVMODE",           TK_RECVMODE,
  "REDIALCOUNT",	TK_REDIALCOUNT,
  "REDIALWAIT", 	TK_REDIALWAIT,
  "REMOVE",		TK_REMOVE,
  "RENAME",		TK_RENAME,
  "REPEAT",		TK_REPEAT,
  "REPLY",		TK_REPLY,
  "REQUEST",		TK_REQUEST,
  "RESTORE",		TK_RESTORE,
  "RESULT",		TK_RESULT,
  "RETURN",		TK_RETURN,
  "REVIEW",		TK_REVIEW,
  "REWIND",		TK_REWIND,
  "RIGHT",		TK_RIGHT,
  "ROL",		TK_ROL,
  "ROR",		TK_ROR,
  "RMDIR",		TK_RMDIR,
  "RTEXT",              TK_RTEXT,
  "RUN",		TK_RUN,
  "SAVE",		TK_SAVE,
  "SCREEN",		TK_SCREEN,
  "SCREENHEIGHT",	TK_SCREENHEIGHT,
  "SCREENWIDTH",	TK_SCREENWIDTH,
  "SCRIPT",		TK_SCRIPT,
  "SCROLL",		TK_SCROLL,
  "SECNO",		TK_SECNO,
  "SECOND",		TK_SECOND,
  "SECONDS",		TK_SECOND,
  "SECRET",		TK_SECRET,
  "SEEK",		TK_SEEK,
  "SEND",		TK_SEND,
  "SENDBREAK",		TK_SENDBREAK,
  "SESSION",		TK_SESSION,
  "SHL",		TK_SHL,
  "SHOW",               TK_SHOW,
  "SHOWACTIVE",         TK_SHOWACTIVE,
  "SHOWINFOBAR",	TK_SHOWINFOBAR,
  "SHOWINPUT",		TK_SHOWINPUT,
  "SHOWKEYBAR",         TK_SHOWMACROBAR,
  "SHOWSTATUSBAR",	TK_SHOWSTATUSBAR,
  "SHOWHSCROLL",	TK_SHOWHSCROLL,
  "SHOWVSCROLL",	TK_SHOWVSCROLL,
  "SHR",		TK_SHR,
  "SIZE",		TK_SIZE,
  "SLICE",		TK_SLICE,
  "SPACE",		TK_SPACE,
  "SPEED",		TK_SPEED,
  "STARTUP",		TK_STARTUP,
  "STATUS",             TK_STATUS,
  "STOPBITS",		TK_STOPBITS,
  "STR",		TK_STR,
  "STRING",		TK_STRINGKEY,
  "STRIP",		TK_STRIP,
  "STROKE",		TK_STROKE,
  "SUBST",		TK_SUBST,
  "SWAP",		TK_SWAP,
  "SWAPDEL",		TK_SWAPDEL,
  "SYSTIME",		TK_SYSTIME,
  "TABEX",		TK_TABEX,
  "TABSTOP",            TK_TABSTOP,
  "TABWIDTH",		TK_TABWIDTH,
  "TERMINAL",		TK_TERMINAL,
  "TERMINATE",		TK_TERMINATE,
  "THEN",		TK_THEN,
  "TICK",		TK_TICK,
  "TICKS",		TK_TICK,
  "TIME",		TK_TIME,
  "TIMES",		TK_MUL,
  "TIMEOUT",		TK_TIMEOUT,
  "TIMING",             TK_TIMING,
  "TOGGLE",             TK_TOGGLE,
  "TRACE",		TK_TRACE,
  "TRAP",		TK_TRAP,
  "TRUE",		TK_TRUE,
  "UNTIL",		TK_UNTIL,
  "UPCASE",		TK_UPCASE,
  "UPLOAD",		TK_UPLOAD,
  "USERID",		TK_USERID,
  "VAL",                TK_INTVAL,
  "VERSION",		TK_VERSION,
  "VISUAL",             TK_VISUAL,
  "WAIT",		TK_WAIT,
  "WATCH",		TK_WATCH,
  "WEEKDAY",		TK_WEEKDAY,
  "WEND",		TK_WEND,
  "WHILE",		TK_WHILE,
  "WINATX",		TK_WINATX,
  "WINATY",             TK_WINATY,
  "WINCHAR",		TK_WINCHAR,
  "WINDOW",		TK_WINDOW,
  "WINDOWWRAP", 	TK_WINDOWWRAP,
  "WINSIZEX",		TK_WINSIZEX,
  "WINSIZEY",		TK_WINSIZEY,
  "WINSTRING",		TK_WINSTRING,
  "WINVERSION", 	TK_WINVERSION,
  "WRITE",		TK_WRITE,
  "XONCHAR",            TK_XONCHAR,
  "XOFFCHAR",           TK_XOFFCHAR,
  "XOR",		TK_BITXOR,
  "XPOS",		TK_XPOS,
  "YPOS",		TK_YPOS
  };

void GenRcData(TOKEN *, int, char *);

main()
{
   GenRcData(tokens, sizeof(tokens)/sizeof(TOKEN), "TOKENS");
}


void GenRcData(vars, items, name)
  TOKEN *vars;
  int	items;
  char	*name;
{
  FILE *file;
  char buf[32];
  int  i;


  printf("%s\n", name);

  strcpy(buf, name);
  strcat(buf, ".DAT");

  printf("%x %x %x %x\n", TK_ABS, TK_ONLINE, TK_TRUE, TK_WHILE);


  file = fopen(buf, "wb");

  for (i = 0; i < items; i++)
    {
    register int j;

    for (j = 0; j <= strlen(vars[i].name); j++)
      fputc(vars[i].name[j], file);

    fputc(vars[i].value, file);
    fputc(vars[i].value >> 8, file);
    }

  fputc(NULL, file);
  fclose(file);
}
