/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  LEXIS(R) 2000 Version 2.5 For Windows
 *
 *      Module:  command.h
 *
 *   Author(s):  Charles E. Kindel, Jr. (cek)
 *
 *
 *      System:  Microsoft C 6.00A, Windows 3.00
 *
 *
 ************************************************************************/
LONG FAR PASCAL ProcessMainCmd( HWND hWnd, WORD wParam, LONG lParam ) ;
void FAR PASCAL NotImplemented( HWND hWnd, WORD wParam, LONG lParam ) ;

/************************************************************************
 * End of File: commmand.h
 ************************************************************************/

