/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  LEXIS(R) 2000 Version 2.5 For Windows
 *
 *      Module:  help.h
 *
 *   Author(s):  Charles E. Kindel, Jr. (cek)
 *
 *
 *      System:  Microsoft C 6.00A, Windows 3.00
 *
 ************************************************************************/

WORD FAR PASCAL Help( WORD wCommand, DWORD dwData, WORD wFlags ) ;

/************************************************************************
 * End of File: help.h
 ************************************************************************/

