/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  LEXIS(R) 2000 Version 2.5 For Windows
 *
 *      Module:  init.h
 *
 *   Author(s):  Charles E. Kindel, Jr. (cek)
 *
 *
 *      System:  Microsoft C 6.00A, Windows 3.00
 *
 *
 ************************************************************************/

/************************************************************************
 * External APIs and data structures
 ************************************************************************/
BOOL FAR PASCAL InitInstance( HANDLE hPrevInst, HANDLE hInstance ) ;
     
HWND FAR PASCAL CreateMainWnd( HANDLE hInstance, int nCmdShow ) ;


/************************************************************************
 * End of File: init.h
 ************************************************************************/

