/************************************************************************
 *
 *    Copyright (C) 1990 Werner Associates.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *     Project:  LEXIS(R) 2000 Version 2.5 For Windows
 *
 *      Module:  print.h
 *
 *   Author(s):  Charles E. Kindel, Jr. (cek)
 *
 *
 *      System:  Microsoft C 6.00A, Windows 3.00
 *
 ************************************************************************/
BOOL FAR PASCAL InitPrinter( HWND hWwnd ) ;
BOOL FAR PASCAL PrinterSetupDialog( HWND hWnd ) ;
BOOL FAR PASCAL PageSetupDialog( HWND hWnd ) ;
BOOL FAR PASCAL PrintFile( HWND hWnd, WORD wFileType ) ;


/************************************************************************
 * End of File: print.h
 ************************************************************************/

