#define ZMODEMDLGBOX                100

#define IDD_DLGFRAME1               0x100

#define IDD_FILENAME                0x200
#define IDD_FILESIZE                0x201
#define IDD_BLOCKCHECK              0x202
#define IDD_TOTALBLOCKS             0x203
#define IDD_TIMEESTIMATE            0x204
#define IDD_RECEIVED                0x205
#define IDD_BYTECOUNT               0x206
#define IDD_BLOCKCOUNT              0x207
#define IDD_CORRECTIONS             0x208
#define IDD_AVERAGECPS              0x209
#define IDD_LASTMESSAGE             0x20A
#define IDD_PROGRESS                0x20B

