/************************************************************************
 *
 *     Project:  
 *
 *      Module:  config.h
 *
 *     Remarks:  
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/

#ifndef _CONFIG_H_
#define _CONFIG_H_

BOOL FAR PASCAL GetDefaultConfig( VOID ) ;
BOOL FAR PASCAL GetConfig( LPSTR lpszCfg ) ;
BOOL FAR PASCAL SaveConfig( LPSTR lpszCfg ) ;


#endif
/************************************************************************
 * End of File: config.h
 ***********************************************************************/

