#define STRICT
#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <cderr.h>
#include <shellapi.h>
#include <sys\types.h>
#include <sys\stat.h>
#ifdef WIN32
#include <drivinit.h>
#else
#include <print.h>
#endif
#include <ddeml.h>
#include <time.h>
#include <stdio.h>
#include <io.h>
#include <direct.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <memory.h>
#include <tdutil.h>
#include <wdb.h>

