/************************************************************************
 *
 *     Copyright (c) 1992 Charles E. Kindel, Jr.  All Rights Reserved.
 *
 *-----------------------------------------------------------------------
 *
 *      Module:  res.h
 *
 ***********************************************************************/
#ifndef _RES_H_
#define _RES_H_

#define IDI_WINPRT2         5000

#define IDM_FILE_EXIT      1000
#define IDM_HELP_ABOUT     2000

#define IDM_TEST_HF      5000
#define IDM_TEST_WRITE     5001
#define IDM_TEST_PAGESETUP     5002
#define IDM_TEST_PRINTERSETUP   5003
#define IDM_TEST_PRINT   5004

#define IDM_WINFILE_INSTALL  6000
#define IDM_WINFILE_REMOVE   6001

#endif

/************************************************************************
 * End of File: res.h
 ***********************************************************************/

