/*** 
*clsid.h
*
*  Copyright (C) 1992, Microsoft Corporation.  All Rights Reserved.
*  Information Contained Herein Is Proprietary and Confidential.
*
*Purpose:
*  This file defines the CLSIDs
*
*Implementation Notes:
*
*****************************************************************************/

#ifndef _CLSID_H_
#define _CLSID_H_

//DEFINE_GUID(CLSID_CFileMgr, 0x16DCFAE0, 0xA69F, 0x1068, 0x83, 0x72, 0x00,0xAA, 0x00, 0x1F, 0x73, 0xC1 ) ;

DEFINE_OLEGUID(CLSID_CFileMgr, 0x16DCFAE0, 0xA69F, 0x1068 ) ;


#endif //_CLSID_H_                 
                 
                 