#define IDD_APPCB          0
#define IDD_NAMEEDIT       1
#define IDD_DOITBTN        2

#define IDM_ABOUT       100
#define IDM_FILE        101
#define IDM_NEWAPP      102
#define IDM_EXIT        103
#define IDM_COPY        104
#define IDM_PASTE       105
#define IDM_DELAPP      106

#define IDD_BOX0        200
#define IDD_BOX1        201
#define IDD_BOX2        202
#define IDD_BOX3        203
#define IDD_BOX4        204
